[package]
name = "parser"
version = "0.1.0"
authors = ["Andreas Tollk√∂tter <andreas.tollkoetter@rwth-aachen.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.9"
lazy_static = "1.4.0"